### ISSUE TITLE
Hidden Doors/items

### ISSUE THREAD

**Issue by ghost** [benprime/crucible-mud#17]
Allow admins to mark a door as hidden.

Doors may be revealed for a set amount of time as the result of a successful search action.

**Comment by nichmack** [comment]
TODO:

Make Hide command.
Hide command should be for all users, not admin only.
Hide command will be for all things that can be hidden - doors, items, etc.
Make different use cases based on parameter entered (door name vs. item name).
Set target to be hidden.
Target remains hidden until found.
Target is only revealed to searching user (unless later create a search spell or share reveal with party/room).
Revealed target is only revealed to searcher until searcher leaves room, then reverts back to hidden.
Revealed status will be stored on the socket, so that it is temporary.
