### ISSUE TITLE
Hide Command

### ISSUE THREAD

**Issue by ghost** [benprime/crucible-mud#27]
Allow users to hide items in a room based on skill level.

Search commands will be required to find them again, even if user who originally hid the item is searching.

**Comment by nichmack** [comment]
TODO:

Make Hide command.
Hide command should be for all users, not admin only.
Hide command will be for all things that can be hidden - doors, items, etc.
Make different use cases based on parameter entered (door name vs. item name).
Set target to be hidden.
Target remains hidden until found.
Target is only revealed to searching user (unless later create a search spell or share reveal with party/room).
Revealed target is only revealed to searcher until searcher leaves room, then reverts back to hidden.
Revealed status will be stored on the socket, so that it is temporary.

**Comment by nichmack** [comment]
Exits/items are set to hidden and no longer appear with the look command.  The hidden target can still be selected by user, however.

**Comment by slashben** [comment]
#72 was merged in to hide doors. Hidden doors must still be made impassible.

**Comment by nichmack** [comment]
also TODO: create spec test file

**Comment by nichmack** [comment]
Hidden doors are unusable.
Hidden doors/items can still be viewed/used by admins.

**Comment by nichmack** [comment]
TODO:  Make hidden items unusable by non admins

**Comment by nichmack** [comment]
#82 All done.
